package Modelo;
// Generated 3 nov. 2021 10:47:30 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Cultivoxlaboreo generated by hbm2java
 */
@Entity
@Table(name="cultivoxlaboreo"
    ,schema="public"
)
public class Cultivoxlaboreo  implements java.io.Serializable {


     private int idcultivoxlaboreo;
     private Cultivo cultivo;
     private Laboreo laboreo;
     private int orden;

    public Cultivoxlaboreo() {
    }

    public Cultivoxlaboreo(Cultivo cultivo, Laboreo laboreo, int orden) {
       this.cultivo = cultivo;
       this.laboreo = laboreo;
       this.orden = orden;
    }
   
     @Id 

    
    @Column(name="idcultivoxlaboreo", unique=true, nullable=false)
     @GeneratedValue(strategy=IDENTITY)
    public int getIdcultivoxlaboreo() {
        return this.idcultivoxlaboreo;
    }
    
    public void setIdcultivoxlaboreo(int idcultivoxlaboreo) {
        this.idcultivoxlaboreo = idcultivoxlaboreo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idcultivo", nullable=false)
    public Cultivo getCultivo() {
        return this.cultivo;
    }
    
    public void setCultivo(Cultivo cultivo) {
        this.cultivo = cultivo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idlaboreo", nullable=false)
    public Laboreo getLaboreo() {
        return this.laboreo;
    }
    
    public void setLaboreo(Laboreo laboreo) {
        this.laboreo = laboreo;
    }

    
    @Column(name="orden", nullable=false)
    public int getOrden() {
        return this.orden;
    }
    
    public void setOrden(int orden) {
        this.orden = orden;
    }




}


