package Modelo;
// Generated 3 nov. 2021 10:47:30 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Estadoproyecto generated by hbm2java
 */
@Entity
@Table(name="estadoproyecto"
    ,schema="public"
)
public class Estadoproyecto  implements java.io.Serializable {


     private int idestadoproyecto;
     private String nombre;
     private Set<Proyecto> proyectos = new HashSet<Proyecto>(0);

    public Estadoproyecto() {
    }

	
    public Estadoproyecto(String nombre) {
        this.nombre = nombre;
    }
    public Estadoproyecto(String nombre, Set<Proyecto> proyectos) {
       this.nombre = nombre;
       this.proyectos = proyectos;
    }
   
     @Id 

    
    @Column(name="idestadoproyecto", unique=true, nullable=false)
     @GeneratedValue(strategy=IDENTITY)
    public int getIdestadoproyecto() {
        return this.idestadoproyecto;
    }
    
    public void setIdestadoproyecto(int idestadoproyecto) {
        this.idestadoproyecto = idestadoproyecto;
    }

    
    @Column(name="nombre", nullable=false, length=30)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="estadoproyecto")
    public Set<Proyecto> getProyectos() {
        return this.proyectos;
    }
    
    public void setProyectos(Set<Proyecto> proyectos) {
        this.proyectos = proyectos;
    }




}


