package Modelo;
// Generated 3 nov. 2021 10:47:30 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.swing.event.ListDataListener;

/**
 * Estadocampo generated by hbm2java
 */
@Entity
@Table(name="estadocampo"
    ,schema="public"
)
public class Estadocampo implements java.io.Serializable {


     private int idestadocampo;
     private String nombre;
     private Set<Campo> campos = new HashSet<Campo>(0);

    public Estadocampo() {
    }

	
    public Estadocampo(String nombre) {
        this.nombre = nombre;
    }
    public Estadocampo(String nombre, Set<Campo> campos) {
       this.nombre = nombre;
       this.campos = campos;
    }
   
     @Id 

    
    @Column(name="idestadocampo", unique=true, nullable=false)
     @GeneratedValue(strategy=IDENTITY)
    public int getIdestadocampo() {
        return this.idestadocampo;
    }
    
    public void setIdestadocampo(int idestadocampo) {
        this.idestadocampo = idestadocampo;
    }

    
    @Column(name="nombre", nullable=false, length=30)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="estadocampo")
    public Set<Campo> getCampos() {
        return this.campos;
    }
    
    public void setCampos(Set<Campo> campos) {
        this.campos = campos;
    }

    @Override
    public String toString() {
        return "Estadocampo{" + "idestadocampo=" + idestadocampo + ", nombre=" + nombre + '}';
    }
}


