package Modelo;
// Generated 3 nov. 2021 10:47:30 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Proyectoxlaboreo generated by hbm2java
 */
@Entity
@Table(name="proyectoxlaboreo"
    ,schema="public"
)
public class Proyectoxlaboreo  implements java.io.Serializable {


     private int idproyectoxlaboreo;
     private Laboreo laboreo;
     private Proyecto proyecto;
     private Date fechainicio;
     private Date fechafin;
     private int orden;

    public Proyectoxlaboreo() {
    }

	
    public Proyectoxlaboreo(Laboreo laboreo, Proyecto proyecto, int orden) {
        this.laboreo = laboreo;
        this.proyecto = proyecto;
        this.orden = orden;
    }
    
    public Proyectoxlaboreo(Laboreo laboreo, Proyecto proyecto, Date fechainicio, Date fechafin, int orden) {
       this.laboreo = laboreo;
       this.proyecto = proyecto;
       this.fechainicio = fechainicio;
       this.fechafin = fechafin;
       this.orden = orden;
    }
   
     @Id 

    
    @Column(name="idproyectoxlaboreo", unique=true, nullable=false)
     @GeneratedValue(strategy=IDENTITY)
    public int getIdproyectoxlaboreo() {
        return this.idproyectoxlaboreo;
    }
    
    public void setIdproyectoxlaboreo(int idproyectoxlaboreo) {
        this.idproyectoxlaboreo = idproyectoxlaboreo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idlaboreo", nullable=false)
    public Laboreo getLaboreo() {
        return this.laboreo;
    }
    
    public void setLaboreo(Laboreo laboreo) {
        this.laboreo = laboreo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idproyecto", nullable=false)
    public Proyecto getProyecto() {
        return this.proyecto;
    }
    
    public void setProyecto(Proyecto proyecto) {
        this.proyecto = proyecto;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fechainicio", length=13)
    public Date getFechainicio() {
        return this.fechainicio;
    }
    
    public void setFechainicio(Date fechainicio) {
        this.fechainicio = fechainicio;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fechafin", length=13)
    public Date getFechafin() {
        return this.fechafin;
    }
    
    public void setFechafin(Date fechafin) {
        this.fechafin = fechafin;
    }

    public int getOrden() {
        return orden;
    }

    public void setOrden(int orden) {
        this.orden = orden;
    }
    
    
}


