package Modelo;
// Generated 3 nov. 2021 10:47:30 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tiposuelo generated by hbm2java
 */
@Entity
@Table(name="tiposuelo"
    ,schema="public"
)
public class Tiposuelo  implements java.io.Serializable {


     private int idtiposuelo;
     private String nombre;
     private Set<Cultivoxtiposuelo> cultivoxtiposuelos = new HashSet<Cultivoxtiposuelo>(0);
     private Set<Lote> lotes = new HashSet<Lote>(0);

    public Tiposuelo() {
    }

	
    public Tiposuelo(String nombre) {
        this.nombre = nombre;
    }
    public Tiposuelo(String nombre, Set<Cultivoxtiposuelo> cultivoxtiposuelos, Set<Lote> lotes) {
       this.nombre = nombre;
       this.cultivoxtiposuelos = cultivoxtiposuelos;
       this.lotes = lotes;
    }
   
     @Id 

    
    @Column(name="idtiposuelo", unique=true, nullable=false)
     @GeneratedValue(strategy=IDENTITY)
    public int getIdtiposuelo() {
        return this.idtiposuelo;
    }
    
    public void setIdtiposuelo(int idtiposuelo) {
        this.idtiposuelo = idtiposuelo;
    }

    
    @Column(name="nombre", nullable=false, length=30)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tiposuelo")
    public Set<Cultivoxtiposuelo> getCultivoxtiposuelos() {
        return this.cultivoxtiposuelos;
    }
    
    public void setCultivoxtiposuelos(Set<Cultivoxtiposuelo> cultivoxtiposuelos) {
        this.cultivoxtiposuelos = cultivoxtiposuelos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tiposuelo")
    public Set<Lote> getLotes() {
        return this.lotes;
    }
    
    public void setLotes(Set<Lote> lotes) {
        this.lotes = lotes;
    }




}


