package Modelo;
// Generated 3 nov. 2021 10:47:30 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Campo generated by hbm2java
 */
@Entity
@Table(name="campo"
    ,schema="public"
)
public class Campo  implements java.io.Serializable {


     private int idcampo;
     private Estadocampo estadocampo;
     private Set<Lote> lotes = new HashSet<Lote>(0);

    public Campo() {
    }

	
    public Campo(Estadocampo estadocampo) {
        this.estadocampo = estadocampo;
    }
    public Campo(Estadocampo estadocampo, Set<Lote> lotes) {
       this.estadocampo = estadocampo;
       this.lotes = lotes;
    }
   
     @Id 

    
    @Column(name="idcampo", unique=true, nullable=false)
     @GeneratedValue(strategy=IDENTITY)
    public int getIdcampo() {
        return this.idcampo;
    }
    
    public void setIdcampo(int idcampo) {
        this.idcampo = idcampo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idestadocampo", nullable=false)
    public Estadocampo getEstadocampo() {
        return this.estadocampo;
    }
    
    public void setEstadocampo(Estadocampo estadocampo) {
        this.estadocampo = estadocampo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="campo")
    public Set<Lote> getLotes() {
        
        return this.lotes;
    }
    
    public void setLotes(Set<Lote> lotes) {
        this.lotes = lotes;
    }
    
    public String verEstadoActualizado() {
        int contLotesConProyectoActivo = 0, contLotesActivos = 0;
        for(Lote l: this.lotes) {
            if(l.isActivo()) {
                contLotesActivos++;
                if(l.tieneProyectoActivo() != null) {
                    contLotesConProyectoActivo++;
                }
            }
        }
        String cadena = null;
        if(contLotesActivos == contLotesConProyectoActivo) {
            cadena = "Completamente trabajado";
        } else if(contLotesConProyectoActivo > 0) {
            cadena = "Parcialmente trabajado";
        } else {
            cadena = "En desuso";
        }
        return cadena;
    }
    
    public boolean estaLibre() {
        boolean libre = false;
        String nombreEstadoCampo = this.getEstadocampo().getNombre();
        if(nombreEstadoCampo.equals("Creado") || nombreEstadoCampo.equals("En desuso")) {
            libre = true;
        }
        return libre;
    }
    
    public boolean estaDadoDeBaja() {
        boolean baja = false;
        String nombreEstadoCampo = this.getEstadocampo().getNombre();
        if(nombreEstadoCampo.equals("Final")) {
            baja = true;
        }
        return baja;
    }
    
}


